name: Portfolio

on:
  push:
    branches: [main]
    paths:
      - '**.html'

  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Get access to your Portfolio code via pre-built actions
      - name: Checkout code
        uses: actions/checkout@v4

      # setup GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # Static code artifacts
      - name: Upload static files
        uses: actions/upload-pages-artifact@v4

      - name: Deploy to Github pages
        id: deployment
        uses: actions/deploy-pages@v4
